////
DIN-proc-technique.adoc

SPDX-FileCopyrightText: 2023 Vincent Corrèze

SPDX-License-Identifier: CC-BY-SA-4.0
////

# Dossier d'installation - procédure technique
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

*Dernière modification* : {docdate}

*Date dernière revue globale* : _<Faire une revue globale du document en fin d'installation et mentionner la date ici>_

*Statut du document* : _<Donner ici le statut, par exemple 'DRAFT', 'FINALISE', etc.>_

## Introduction

La procédure technique d'installation indique les modalités et les conditions de validation de l'installation en production de l'outil.

## Documents de référence

.Documents internes
[cols="1,3,1"]
|===
| Nom | titre/URi du document | Version

| PSSI | Politique de sécurité | 2.3.0

| DA | link:../README.adoc[Dossier applicatif] | 1.0.2

|===

## Procédure technique d'installation

[TIP]
====
la procédure technique d'installation indique précisément chaque opération technique réalisée durant le déploiement, et les *choix opérés* dans les utilitaires d'installation (par exemple le choix d'un encodage par défaut pour l'installation d'un système de gestion de base de données).

Ce document peut aussi pointer directement vers une documentation d'installation disponible (en ligne, ou fournie par un intégrateur).
====

====
*Exemple* : On installe le module SGBD MariaDB en activant l'encodage `utf8-general-ci`
====

## Modalités d'accès et profils

[TIP]
====
Fournir une synthèse des principaux profils utilisateurs de l'application, ainsi qu'une indication du coffre-fort d'authentification utilisé.
====

## Déploiement du client

[TIP]
====
décrire ici les modalités techniques de déploiement des modules clients de l'application. Ces modules peuvent nécessiter l'installation préalable de librairies, framework ou autre module qu'il est important de décrire ici. On précisera les choix à opérer dans les modules d'installation.
====

====
*Exemple 1* : le déploiement auprès des clients se fera par l'affichage d'une url pointant vers le serveur.
====

====
*Exemple 2* : le déploiement du client nécessite l'installation de python3.11 sur les postes des utilisateurs. On exécute ensuite le client de l'application en laissant toutes les options par défaut.
====

## Contrôle de conformité technique

[TIP]
====
Une checklist, ou une procédure complète de test doit permettre de vérifier la conformité technique de l'outil à l'architecture prévue dans le dossier d'architecture.

Ces tests de conformité doivent aussi intégrer le respect des conditions de sécurité de l'application.
====
