////
exemple-dossier-installation.adoc

SPDX-FileCopyrightText: 2023 Vincent Corrèze

SPDX-License-Identifier: CC-BY-SA-4.0
////

# Dossier d'installation
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

*Dernière modification* : {docdate}

*Date d'installation* : _<Faire une revue globale du document en fin d'installation et mentionner la date ici>_

*Statut du document* : _<Donner ici le statut, par exemple 'DRAFT', 'FINALISE', etc.>_

## Documents de référence

.Documents internes
[cols="1,3,1"]
|===
| Nom | titre/URi du document | Version

| PSSI | https://monintranet/pssi | 2.0.4

|===

## Déroulement de l'installation

### Rôles et coordonnées des interlocuteurs

Les interlocuteurs sont identiques à ceux indiqués dans le DEX.

### Modalités de mise en production

Le plan de test fonctionnel a validé le bon fonctionnement de l'environnement de recette le 15/10/2022. L'installation de l'instance de production s'est effectuée le 25/10/2022.

La bascule en production a été réalisée le 27/10/2022.

### Déroulement technique de l'installation

L'installation s'est déroulé selon la procédure éditeur. Le choix de langue a été _Français_. Le choix de fuseau horaire d'enregistrement était _UTC+1_

### Transfert de données

Aucune donnée n'a été réintégrée dans l'application. Le paramétrage a été saisi dans la base de test avant la recette.

### Modalités d'accès et profils de référence

Le profil administrateur central a pour nom : `admin_main`. Les membres du groupe AD "Administrateurs du domaine" on un accès administrateur à l'application.

#### Planification de l'installation

La mise en production a été réalisée en séance le 27/10.

## Vérification d'aptitude au bon fonctionnement

### Contrôle de conformité technique

L'environnement technique est confirmé comme suit (cf. dossier d'architecture):

* [x] Dimensionnement de la machine : 50 Go HDD/2vCPU/8Go RAM
* [x] versions des composants
* [x] gestion du démarrage : ok via systemd
* [x] gestion de la sauvegarde : ok via plan de sauvegarde

### Plan de test fonctionnel

Le plan de test est référencé dans l'outil https://squashtm.monentreprise.net.

### Recette

La recette fonctionnelle a été prononcée comme suit:

* Date de recette : 28/10/2021
* Valideurs : Julie Julejule, responsable applicative
* Réserves : aucune.
