////
guide-dossier-installation.adoc

SPDX-FileCopyrightText: 2023 Vincent Corrèze

SPDX-License-Identifier: CC-BY-SA-4.0
////

# Dossier d'installation
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

NOTE: Lisez ce document avant de travailler sur le modèle correspondant.

## Introduction

Le dossier d'installation indique les modalités et conditions de mise en production d'un logiciel.

## Audience

L'audience cible d'un dossier d'installation est l'équipe d'exploitation système qui aura à connaître les paramètres utilisés à l'installation. Le document s'adresse donc à une audience technique, connaissant l'environnement et le fonctionnement basique de l'environnement d'exploitation. Au besoin, les compétences techniques nécessaires sont décrites dans le DMV, ou dans le DEX. ou au moins référencées dans le link:../DEX/guide-dossier-exploitation.adoc[dossier d'exploitation].

## Pourquoi un dossier d'installation

Ce dossier *n'est pas* un guide pour installer de nouveau le logiciel (c'est le rôle d'une documentation du fournisseur de l'outil, qu'il s'agisse d'équipe de développement de l'entreprise ou externalisées, ou d'un éditeur, ou d'un groupe collaboratif éditeur de logiciel).

Ce dossier regroupe les actions et procédures qui *ont été* réalisées lors de l'installation du logiciel. Il a vocation à enregistrer les choix et opérations réalisées à l'installation et à permettre le contrôle du respect de la configuration technique de l'outil.

L'organisation et le pilotage de la mise en production de l'outil relèvent de la gestion du projet de mise en oeuvre, et ne sont généralement pas réalisées par les équipes de production. La co-construction de ce dossier, bilan de l'installation, permet d'assurer le transfert de compétence entre les 2 équipes.

## Écrire la procédure

### _Introduction_

Ce dossier indique les modalités et les conditions de validation de l'installation en production de l'outil.

Il est important d'identifier le statut, la date de dernière modification et la date de dernière revue du document.

### _Documents de référence_

Dans cette section, reportez les documents de référence généraux relatifs à l'application.

### _Déroulement de l'installation_

#### _Rôles et coordonnées des interlocuteurs_

Les rôles liés à l'installation sont souvent décrits dans le dossier d'exploitation global. A défaut, indiquer les acteurs ayant effectivement réalisé l'installation.

### _Modalités de mise en production_

Décrire ici les modalités organisationnelles de mise en production. On s'intéresse ici aux personnes, aux processus et aux jalons de mise en oeuvre, pour aboutir à un outil opérationnel.

#### _Déroulement technique de l'installation_

Indiquer précisément chaque opération technique réalisée durant le déploiement, et les *choix opérés* dans les utilitaires d'installation (par exemple le choix d'un encodage par défaut pour l'installation d'un système de gestion de base de données).

Ce document peut aussi pointer directement vers une documentation d'installation disponible (en ligne, ou fournie par un intégrateur).

#### _Transfert de données_

Indiquer les différents transferts de données ayant pu avoir lieu dans la mise en production, qu'il s'agisse d'un ancien outil ou d'une saisie de paramétrage.

En particulier, si des erreurs ont été rencontrées ou des jeux de données chargés de façon incomplète, les préciser permet de connaître précisément le périmètre de reprise.

#### _Modalités d'accès et profils de référence_

Fournir une synthèse des principaux profils utilisateurs de l'application, ainsi qu'une indication du coffre-fort d'authentification utilisé.

#### _Déploiement_

On rappelle ici le plan de déploiement de l'application (opérations, formations des utilisateur.rices).

On indique aussi les modalités techniques de déploiement des modules client de l'application. Ces modules peuvent nécessiter l'installation préalable de librairies, framework ou autre module qu'il est important de décrire ici. On précisera les choix à opérer dans les modules d'installation.

#### _Planification de l'installation_

Donner ici l'organisation et la planification de l'installation effectués dans la phase projet.

Ces éléments permettent en exploitation de connaître les opérations réalisées, et de capitaliser sur la pratique.

### _Vérification d'aptitude au bon fonctionnement_

#### _Contrôle de conformité technique_

Une checklist, ou une procédure complète de test doit permettre de vérifier la conformité technique de l'outil à l'architecture prévue dans le dossier d'architecture.

Ces tests de conformité doivent aussi intégrer le respect des conditions de sécurité de l'application.

#### _Plan de test fonctionnel_

Il est important que l'outil nouvellement implémenté soit testé, sur un plan fonctionnel, par ses utilisateur.rices finales qui doivent valider que les fonctions attendues correspondent au besoin exprimé dans le dossier d'architecture ou le cahier des charges. Ces tests doivent faire référence aux _exigences_ du système et correspondre à un jeu de données précis (_cas de test_). Ceci permet d'exécuter plusieurs _campagnes de test_ afin de lever toutes les non-conformités fonctionnelles.

Le document d'installation doit mentionner _a minima_ une synthèse des tests effectués, afin de confirmer le bon fonctionnement global du système.

Cet ensemble de test peut faire l'objet d'un plan de test complet et détaillé, pour lequel on pourra se tourner vers un outil de gestion des tests comme link:https://www.squashtest.com/[SquashTest] ou link:https://kiwitcms.org/[KiwiTCMS].

#### _Recette_

Le dossier doit indiquer la date précise de la recette, fonctionnelle et technique, ainsi que les éventuelles réserves émises par l'entreprise à l'installation.
