////
README.adoc

SPDX-FileCopyrightText: 2023 Vincent Corrèze

SPDX-License-Identifier: CC-BY-SA-4.0
////

# README - Dossier Applicatif

:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

## Description du projet

Ce modèle recense les principales documentations techniques nécessaires pour assurer le fonctionnement courant d'une application informatique au sein d'un système d'informations.

Il s'inspire fortement du link:https://github.com/bflorat/modele-da[modèle de dossier d'architecture] de Bertrand Florat qu'il complète et étend.

## Pour qui ?

Ce projet est destiné aux équipes d'exploitation informatique, pour qu'elles puissent documenter précisément tous les éléments de fonctionnement courant de leurs applicatifs de production.

## Prérequis

Ces modèles nécessitent une connaissance des contraintes de l'exploitation courante des applicatifs de production.

## Principes du modèle
Le dossier d'architecture et ses 5 vues (développement, dimensionnement, applicative, sécurité, infrastructure) a vocation à documenter la phase de conception d'une application. Il constitue l'un des modules de ce dossier, permettant aux rôles concernés (ops, intégrateurs, RSSI) de retrouver le détail fin de la conception de l'application. Dans la chaîne de valeur des services  ITIL il correspond à la phase de "conception & transition".

Les équipes qui assurent le fonctionnement courant des applications ("Ops", "exploitants", "administrateurs", etc.) doivent, sans avoir besoin de connaître l'intégralité du dossier d'architecture, pouvoir disposer des informations essentielles nécessaires au fonctionnement de l'outil dans le contexte précis du SI où l'application s'intègre. Les équipes doivent aussi pouvoir retrouver les éléments précis de l'implémentation réelle de l'application, et les modalités de son évolution. Ces éléments correspondent aux phases "construire" et "Fournir et soutenir" de la chaîne de valeur des services selon ITIL v4.

Pour COBIT 2019, ces documentations font partie des domaines BAI (Bâtir, acquérir, implémenter) et DSS (Délivrer, Servir et Soutenir)

Ces informations sont réparties dans plusieurs dossiers :

.Dossiers du modèle
[cols="1a,3a,1a,1a"]
|===
^| Dossier ^| Description ^| Emplacement chaîne de valeur ITIL ^|Processus COBIT

| link:DA/[Dossier d'architecture] | Il détaille l'architecture complète de l'application. Il est composé soit de l'ensemble des vues exposées plus haut, soit d'une synthèse applicable à l'application (p. ex si elle est fournie par l'éditeur) | Conception & transition | BAI03, BAI04, BAI06

| link:DIN/[dossier d'installation]| Il détaille les modalités précises et concrètes de la première installation de l'application. Cela permet de vérifier sa conformité au document d'architecture. | Obtenir/Construire | BAI10

| link:DEX/dossier-exploitation.adoc[dossier d'exploitation] | Il détaille les procédures et informations utiles et nécessaires au bon fonctionnement de la solution | Fournir et soutenir| DSS01

| link:DMV/[dossier de montée de version] | Il détaille les informations techniques et opérationnelles nécessaires pour mettre à jour la version. Il définit la continuité de fonctionnement du service. | Fournir et soutenir | BAI06, DSS04

|===

Les modalités d'acquisition des solutions techniques sont telles que généralement, l'ensemble des éléments de documentation présentés ici ne sont pas disponibles. Par exemple, lors de l'implémentation d'un outil logiciel d'éditeur le détail de la vue architecture applicative est rarement fourni, et le dossier technique de montée de version est réservé à l'éditeur.

Il est donc fréquent que le dossier de documentation applicative soit partiel ou incomplet. Cependant nous recommandons que *toute application en production dispose _a minima_ d'un dossier d'exploitation*.

Le dossier comprends également un exemple de glossaire, à l'image de celui du dossier d'architecture. Il est entendu qu'un dossier complet ne doit contenir qu'un seul glossaire.

## Instructions pour utiliser le modèle

Les modèles sont rédigés au format https://asciidoc.org[asciidoc]. De la même façon que pour le dossier d'architecture, nous préconisons un format *textuel et lisible* (type markdown), dont le suivi de version peut être facilement implémenté dans un outil dédié ce qui permet de maintenir la documentation.

Les modèles proposés sont rédigés selon les pratiques du projet link:https://thegooddocsproject.dev[The good docs project].

Chaque modèle contient :

- Un fichier `guide-xxx.adoc`, qui fournit les explications détaillées concernant chaque chapitre du modèle
- un fichier `modele-xxx.adoc`, qui constitue le modèle brut avec une description sommaire de chaque partie
- un fichier `exemple-xxx.adoc` qui décrit un faux projet à titre d'exemple.

Chaque document correspond à son besoin propre, et doit pouvoir être consulté sans être contraint de se référer à d'autres document. Les liens vers d'autres documentation (dossier d'architecture en particulier, ou documentation en ligne) ne doivent être présents que pour servir de référence ou diagnostiquer un point précis.

Chacune des documentations est autoporteuse, de façon que l'intervenant.e puisse n'ouvrir que la documentation concernée. Des liens pertinents permettent de renvoyer d'un document à l'autre en cas de besoin.

Les recommandations d'écriture sont regroupées dans le link:./guide-ecriture.adoc[guide d'écriture].

### Que ne trouve-t-on *PAS* dans ce document ?

* les *règles d'exploitation de référence* (communes à toutes les applications);
* les *documentations utilisateurs* : le dossier applicatif concerne l'exploitation (maintien en conditions opérationnelles et de sécurité) de l'application, il ne recense pas de documents destinés aux utilisateurs fonctionnels.

## Contribuer

Les modèles proposés sont évidemment perfectibles, et toute proposition d'amélioration est la bienvenue.

Les contributions sont attendues sous la forme de tickets où de push request github.

## Conditions d'utilisation

* Copyright (c) 2023 Vincent Corrèze et contributeurs
* Ce modèle est soumis à la licence https://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0] : Creative Commons Attribution - Partage à l'identique V4.0
* Le modèle de dossier d'architecture utilisé est (c) Bertrand Florat et contributeurs, il est soumis à la licence https://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0].
* Vous pouvez créer votre propre modèle issu de celui-ci dès lors :
** qu'il soit redistribué sous la même licence et mentionne un lien vers https://creativecommons.org/licenses/by-sa/4.0/
** qu'il précise le nom du créateur (Vincent Corrèze)
** qu'il renvoie par un lien hypertexte vers link:https://github.com/vcorreze/modele-dossierapplicatif[] et assure une mention effective de sa paternité (source et date de consultation, ou identifiant du commit utilisé).
* Un dossier issu de ces modèles n'a pas à appliquer ces licences. Il est cependant recommandé d'y inclure un lien vers link:https://github.com/vcorreze/modele-dossierapplicatif[] et/ou vers link:https://github.com/bflorat/modele-da[].

## Remerciements

* Bertrand Florat, pour l'inspiration et le modèle de dossier d'architecture
