////
DMV-proc-fonctionnelle.adoc

SPDX-FileCopyrightText: 2023 Vincent Corrèze

SPDX-License-Identifier: CC-BY-SA-4.0
////

# Dossier de Montée de Version - procédure fonctionnelle
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

*Dernière modification* : {docdate}

*Date dernière revue globale* : _<Faire une revue globale du document à chaque fin de montée de version et mentionner la date ici>_

*Statut du document* : _<Donner ici le statut, par exemple 'DRAFT', 'FINALISE', etc.>_

## Introduction

La procédure fonctionnelle de montée de version indique les modalités et les conditions de validation d'une montée de version de l'outil.

## Documents de référence

.Documents internes
[cols="1,3,1"]
|===
| Nom | titre/URi du document | Version

| PSSI | Politique de sécurité | 2.3.0

| DA | link:../README.adoc[Dossier applicatif] | 1.0.2

|===

## Test de la nouvelle version

[TIP]
====
Les modalités de test d'une nouvelle version permettent en particulier de vérifier que les modules utilisés de l'application sont encore fonctionnels (non-régression).

Ce plan de test doit avoir été défini dès l'installation, et pour assurer une couverture fonctionnelle complète il est nécessaire qu'il soit reproduit à chaque montée de version.

Il faut penser à intégrer aux tests les nouvelles fonctionnalités souhaitées de la nouvelle version.

Si des tests fonctionnels sont effectués de façon étendue, le plan de test peut être amené à devenir un document spécifique du dossier applicatif.

Il est crucial que toute application dispose d'un environnement de test ou/et de pré-production sur lequel l'ensemble du plan de test pourra être déroulé sans impacter la production.
====

### Recette

[TIP]
====
On indiquera précisément la (les) date(s) précises des recettes validation les nouvelles version installées.

Cet historique ne doit pas remplacer un fichier changelog de développement. Il indique uniquement les versions ayant fait l'objet d'une recette fonctionnelle et qui sont validées en production, dans une logique d'homologation *métier* de la version installée.
====

.Montées de version
[cols="1,^1,^2,3"]
|===
| Date | Version | Valideur | Commentaire

| | | |
|===

====
Exemple :
[cols="1,^1,^2,3"]
|===
| Date | Version | Valideur | Commentaire

| 20230402 | 1.3.5 | Resp. métier | bug #55438 restant.
| 20230503 | 1.4.0 | Resp. métier | ajout du module impression pdf.
|===
====

## Modalités de montée de version

### Rôles et coordonnées des interlocuteurs

[TIP]
====
Les rôles liés à la montée de version sont généralement les mêmes qu'à l'installation. On peut ici renvoyer directement au paragraphe idoine du dossier d'installation, ou du dossier d'exploitation global.
====

### Organisation de la montée de version.

[TIP]
====
Décrire ici les modalités organisationnelles de la montée de version. Celles-ci sont généralement une version réduite ou amendée de la link:../DIN/DIN-proc-fonctionnelle.adoc[Procédure fonctionnelle d'installation].
====

### Déploiement

[TIP]
====
Décrire ici les modalités de déploiement de la nouvelle version. Il faut en particulier prendre en compte les temps de déploiement technique et les temps de formation des personnes.
====

### Plan de communication

[TIP]
====
Donner ici les jalons et les modalités concrètes d'information des différents acteurs sur l'avancement de la montée de version. Il faut en particulier porter attention aux messages qui informeront les utilisateur.rices finaux de la bascule vers la nouvelle version, et des modalités de support autour de l'application.
====

### Planification

[TIP]
====
Planifier précisément l'ensemble des phases de la mise en production. On intègre bien sûr ici les temps d'installation et de déploiement qui relèvent de la procédure technique d'installation.

On étudiera en particulier les temps d'indisponibilité des outils (ancien, nouveau) et les temps de communication aux utilisateur.rices. Ce planning permet aussi de confirmer les moments où sont mobilisés les interlocuteur.rices du projet.
====

### Retour arrière

[TIP]
====
Décrire ici les modalités organisationnelles d'un retour arrière. En particulier il faut définir à l'avance qui prends la décision, comment elle est communiquée et sous quel délai l'opération doit être réalisée.

On décrira aussi si besoin les modalités de reprise des éléments éventuellement saisis dans la nouvelle version.
====
