////
guide-DMV-proc-fonctionnelle.adoc

SPDX-FileCopyrightText: 2023-2024 Vincent Corrèze

SPDX-License-Identifier: CC-BY-SA-4.0
////

# Guide pour la procédure de montée de version
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

NOTE: Lisez ce document avant de travailler sur le modèle correspondant.

## Introduction

Une procédure fonctionnelle de montée de version couvre les modalités et conditions d'une montée de version de l'outil.

## Audience

L'audience cible d'un dossier de montée de version est l'équipe d'exploitation système qui aura à assurer ces opérations. Le document s'adresse donc à une audience technique, connaissant l'environnement et le fonctionnement basique de l'environnement d'exploitation. Au besoin, les compétences techniques nécessaires sont décrites dans le DMV, ou référencées dans le link:../DEX/guide-dossier-exploitation.adoc[dossier d'exploitation].

## Pourquoi une procédure de montée de version ?

Cette procédure regroupe les actions et procédures qui doivent être envisagés et réalisés lors toute montée de version. Elle couvre à la fois la procédure fonctionnelle (quels utilisateurs, planification, préparation, recette, validation) et la procédure technique (les opérations concrètes de montée de version). Cela permet de rendre l'action homogène d'une version à l'autre, et de garantir un déroulement fluide de la montée de version.

## Écrire la procédure

On indiquera toujours en début de document les dates de dernière modification, de dernière revue globale et le statut du document. Cela permet de vérifier l'actualité et la validité de la procédure.

### _Introduction_

Cette section indique le but de la procédure, et le nom du service concerné.

### _Documents de référence_

Dans cette section, reportez les documents de référence généraux relatifs à l'application.

### _Plan de test de la nouvelle version_

Les modalités de test d'une nouvelle version permettent en particulier de vérifier que les modules et les fonctions métier de l'application sont encore fonctionnels (non-régression).

Ce plan de test doit avoir été défini dès l'installation, et pour assurer une couverture fonctionnelle complète il est nécessaire qu'il soit reproduit à chaque montée de version.

Il est pertinent que le plan de test soit rédigé sous la forme d'*exigences* et de *scénarios de test*. Cette formulation permet de garantir la répétabilité des tests.

Il faut penser à intégrer aux tests les nouvelles fonctionnalités souhaitées de la nouvelle version.

Si des tests fonctionnels sont effectués de façon étendue, le plan de test peut être amené à devenir un document spécifique du dossier applicatif.

Il est crucial que toute application dispose d'un environnement de test ou/et de pré-production sur lequel l'ensemble du plan de test pourra être déroulé sans impacter la production.

### _Modalités de montée de version_

Les évolutions de version d'une application sont généralement effectuées selon trois modalités :

- Mise à jour directement sur l'instance de production
- Construction d'une instance parallèle et migration
- livraison continue d'évolutions poussées en production, généralement par un outil dédié (DevOps).

Quelle que soit la modalité concernée, les éléments ci-dessous doivent être préparés pour assurer une montée de version.

#### _Rôles et coordonnées des interlocuteurs_

Les rôles liés à la montée de version sont généralement les mêmes qu'à l'installation. On peut renvoyer directement au paragraphe idoine du dossier d'installation, ou du dossier d'exploitation global. A défaut, ils doivent être précisés ici.

#### _Organisation de la montée de version_

Les modalités de la montée de version sont généralement une version réduite ou amendée de la *Procédure d'installation*.

##### _Sauvegarde de la production_

*Toute montée de version doit s'assurer de disposer d'une sauvegarde de l'environnement de production*.

Il est généralement utile de disposer d'une sauvegarde dédiée *au moment du déclenchement* de l'opération technique, pour disposer des données les plus fraîches et de l'applicatif effectivement en production au moment de l'opération (_tout n'est pas toujours documenté..._)

On sauvegardera si possible :

- Les *données*, dans le format utilisé par l'applicatif (_dump_ de base par exemple)
- L'*applicatif* (répertoire de l'application, ou _dump_ applicatif s'il est prévu)
- L'*environnement* c'est à dire l'ensemble des couches de fonctionnement de l'application. Ceci correspond souvent à utiliser les possibilités de snapshot dans les environnement virtualisés ou de _dump_ des conteneurs en environnement conteneurisé.

##### _Opérations de montée de version_

Décrire ici le déroulement technique de la montée de version. Ce déroulement peut renvoyer vers des documentations en ligne ou une documentation éditeur.

##### _Déploiement_

Décrire les modalités de déploiement de la nouvelle version. Il faut en particulier prendre en compte les modalités de déploiement technique et les temps de formation des personnes.

#### _Planification_

Planifier précisément l'ensemble des phases de la mise en production. On intègre bien sûr les temps d'installation et de déploiement.

On étudiera en particulier les temps d'indisponibilité des outils (ancien, nouveau) et les temps de communication aux utilisateur.rices. Ce planning permet aussi de confirmer les moments où sont mobilisés les interlocuteur.rices du projet.

#### _Plan de communication_

Donner plus précisément les jalons et les modalités concrètes d'information des différents acteurs sur l'avancement de la montée de version. Il faut en particulier porter attention aux messages qui informeront les utilisateur.rices finaux de la bascule vers la nouvelle version, et des modalités de support autour de l'application.

#### _Retour arrière_

Décrire les modalités organisationnelles et techniques d'un retour arrière. En particulier il faut définir à l'avance qui prends la décision, comment elle est communiquée et sous quel délai l'opération doit être réalisée.

La procédure technique doit disposer des consignes explicites pour réaliser un retour à la version antérieure. Les différentes modalités de sauvegarde, les nombreuses utilitaires permettent généralement plusieurs manières de reconstruire l'environnement de production.

Dans le stress d'une décision de retour arrière, les intervenant.es doivent disposer d'un déroulé clair et testé de la méthode choisie pour le retour arrière.

On décrira aussi si besoin les modalités de reprise des éléments éventuellement saisis dans la nouvelle version.

#### _Recette_

Ce paragraphe sert à historiser les montées de versions réalisées sur l'application.

Cet historique ne doit pas remplacer un fichier changelog de développement. Il indique uniquement les versions ayant fait l'objet d'une recette fonctionnelle et qui sont validées en production, dans une logique d'homologation *métier* de la version installée.

On indiquera la (les) date(s) précises des recettes validation les nouvelles version installées.
